version: "3.9"

services:
  identity-svc:
    build: ./src/IdentityService
    container_name: nwsdb-identity-service
    ports:
      - "5021:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - nwsdb-net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  payment-svc:
    build: ./src/PaymentService
    container_name: nwsdb-payment-service
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - nwsdb-net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  usage-svc:
    build: ./src/UsageService
    container_name: nwsdb-usage-service
    ports:
      - "5010:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - nwsdb-net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  client-app:
    build: ./client
    container_name: nwsdb-client
    ports:
      - "8080:80"
    depends_on:
      - identity-svc
      - payment-svc
      - usage-svc
    networks:
      - nwsdb-net

networks:
  nwsdb-net:
    driver: bridge
